<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- Copyright 2026 Sungwoo Kang -->
<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.0.5</Version>
    <AssemblyVersion>0.0.5.0</AssemblyVersion>
    <FileVersion>0.0.5.0</FileVersion>
    <InformationalVersion>0.0.5</InformationalVersion>
    <Authors>Sungwoo Kang</Authors>
    <Copyright>Copyright 2026 Sungwoo Kang</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/SKang393/GraphAutoReader</RepositoryUrl>
  </PropertyGroup>
</Project>
