# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Sungwoo Kang

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$EvidenceRoot,

    [Parameter(Mandatory = $true)]
    [string]$DestinationRoot,

    [Parameter(Mandatory = $true)]
    [string]$ExpectedCommit,

    [Parameter(Mandatory = $true)]
    [string]$ExpectedVersion,

    [string]$RepositoryRoot
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
    $RepositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
}
else {
    $RepositoryRoot = [IO.Path]::GetFullPath($RepositoryRoot)
}
$EvidenceRoot = [IO.Path]::GetFullPath($EvidenceRoot)
$DestinationRoot = [IO.Path]::GetFullPath($DestinationRoot)
$repositoryPrefix = $RepositoryRoot.TrimEnd('\', '/') + [IO.Path]::DirectorySeparatorChar
$releaseAuditPath = Join-Path $RepositoryRoot 'packaging\common\release-audit.json'
$installerPath = Join-Path $RepositoryRoot 'packaging\opencv-source\Install-ReviewedRuntime.ps1'
$cleanMachineHarnessPath = Join-Path $RepositoryRoot 'packaging\clean-machine\Invoke-GraphReaderCleanMachineValidation.ps1'

foreach ($required in @($releaseAuditPath, $installerPath, $cleanMachineHarnessPath)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "Release OpenCV input is missing: $required"
    }
}
if ($ExpectedCommit -notmatch '^[0-9a-f]{40}$' -or
    $ExpectedVersion -notmatch '^\d{1,2}\.\d{1,2}\.\d{1,2}$') {
    throw 'Release OpenCV evidence requires a canonical expected commit and version.'
}

function Get-RequiredJsonProperty {
    param(
        [Parameter(Mandatory = $true)][object]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) {
        throw "$Description is missing required property '$Name'."
    }
    return $property.Value
}

function Assert-JsonBoolean {
    param(
        [Parameter(Mandatory = $true)][object]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][bool]$Expected,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $value = Get-RequiredJsonProperty -Object $Object -Name $Name -Description $Description
    if (-not ($value -is [bool]) -or [bool]$value -ne $Expected) {
        throw "$Description property '$Name' must be the JSON Boolean '$Expected'."
    }
}

function Assert-CanonicalSha256 {
    param(
        [AllowNull()][object]$Value,
        [Parameter(Mandatory = $true)][string]$Description
    )

    if (-not ($Value -is [string]) -or [string]$Value -cnotmatch '^[0-9a-f]{64}$') {
        throw "$Description must be a canonical lowercase SHA-256 value."
    }
}

function Assert-CleanMachineEvidence {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$ExpectedNativeSha256,
        [Parameter(Mandatory = $true)][string]$ExpectedHarnessSha256,
        [Parameter(Mandatory = $true)][string]$ExpectedExecutableSha256
    )

    $evidence = Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
    if ([string](Get-RequiredJsonProperty -Object $evidence -Name 'schema' -Description 'OpenCV clean-machine evidence') -cne
        'graphreader.opencv-clean-machine-load.v1' -or
        [string](Get-RequiredJsonProperty -Object $evidence -Name 'status' -Description 'OpenCV clean-machine evidence') -cne 'pass') {
        throw 'OpenCV clean-machine evidence schema or status is not directly passing.'
    }
    Assert-CanonicalSha256 -Value (Get-RequiredJsonProperty -Object $evidence -Name 'harnessSha256' -Description 'OpenCV clean-machine evidence') -Description 'OpenCV clean-machine harness checksum'
    if ([string]$evidence.harnessSha256 -cne $ExpectedHarnessSha256) {
        throw 'OpenCV clean-machine evidence was not generated by the current reviewed harness.'
    }
    if (@(Get-RequiredJsonProperty -Object $evidence -Name 'failures' -Description 'OpenCV clean-machine evidence').Count -ne 0) {
        throw 'OpenCV clean-machine evidence retains one or more failures.'
    }

    $payload = Get-RequiredJsonProperty -Object $evidence -Name 'payload' -Description 'OpenCV clean-machine evidence'
    if ([string](Get-RequiredJsonProperty -Object $payload -Name 'commit' -Description 'Clean-machine payload') -cne $ExpectedCommit -or
        [string](Get-RequiredJsonProperty -Object $payload -Name 'version' -Description 'Clean-machine payload') -cne $ExpectedVersion) {
        throw 'Clean-machine payload does not bind the release commit and version.'
    }
    Assert-JsonBoolean -Object $payload -Name 'dirty' -Expected $false -Description 'Clean-machine payload'
    Assert-JsonBoolean -Object $payload -Name 'portableModePresent' -Expected $true -Description 'Clean-machine payload'
    $payloadExecutableSha256 = Get-RequiredJsonProperty -Object $payload -Name 'executableSha256' -Description 'Clean-machine payload'
    $payloadOpenCvSha256 = Get-RequiredJsonProperty -Object $payload -Name 'openCvSha256' -Description 'Clean-machine payload'
    Assert-CanonicalSha256 -Value $payloadExecutableSha256 -Description 'Clean-machine payload executable checksum'
    Assert-CanonicalSha256 -Value $payloadOpenCvSha256 -Description 'Clean-machine payload OpenCV checksum'
    if ([string]$payloadExecutableSha256 -cne $ExpectedExecutableSha256 -or
        [string]$payloadOpenCvSha256 -cne $ExpectedNativeSha256 -or
        [int](Get-RequiredJsonProperty -Object $payload -Name 'modelPayloadFileCount' -Description 'Clean-machine payload') -ne 0 -or
        [int](Get-RequiredJsonProperty -Object $payload -Name 'reparsePointCount' -Description 'Clean-machine payload') -ne 0) {
        throw 'Clean-machine payload bytes or containment policy differ from the release boundary.'
    }

    $nativeLoad = Get-RequiredJsonProperty -Object $evidence -Name 'nativeLoad' -Description 'OpenCV clean-machine evidence'
    Assert-JsonBoolean -Object $nativeLoad -Name 'attempted' -Expected $true -Description 'OpenCV native load'
    Assert-JsonBoolean -Object $nativeLoad -Name 'succeeded' -Expected $true -Description 'OpenCV native load'
    if ([string](Get-RequiredJsonProperty -Object $nativeLoad -Name 'flags' -Description 'OpenCV native load') -cne
        'LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_DEFAULT_DIRS' -or
        $null -ne (Get-RequiredJsonProperty -Object $nativeLoad -Name 'win32Error' -Description 'OpenCV native load')) {
        throw 'OpenCV native load did not use the required loader boundary.'
    }

    $smoke = Get-RequiredJsonProperty -Object $evidence -Name 'applicationSmoke' -Description 'OpenCV clean-machine evidence'
    Assert-JsonBoolean -Object $smoke -Name 'passed' -Expected $true -Description 'Application smoke'
    Assert-JsonBoolean -Object $smoke -Name 'timedOut' -Expected $false -Description 'Application smoke'
    if ([string](Get-RequiredJsonProperty -Object $smoke -Name 'argument' -Description 'Application smoke') -cne '--portable-smoke' -or
        [int](Get-RequiredJsonProperty -Object $smoke -Name 'exitCode' -Description 'Application smoke') -ne 0) {
        throw 'Application smoke did not complete the required portable path.'
    }

    $machine = Get-RequiredJsonProperty -Object $evidence -Name 'machine' -Description 'OpenCV clean-machine evidence'
    Assert-JsonBoolean -Object $machine -Name 'is64BitOperatingSystem' -Expected $true -Description 'Clean Windows machine'
    Assert-JsonBoolean -Object $machine -Name 'is64BitProcess' -Expected $true -Description 'Clean Windows machine'
    Assert-JsonBoolean -Object $machine -Name 'networkQuerySucceeded' -Expected $true -Description 'Clean Windows machine'
    $installAgeHours = [double](Get-RequiredJsonProperty -Object $machine -Name 'installAgeHours' -Description 'Clean Windows machine')
    if ([string](Get-RequiredJsonProperty -Object $machine -Name 'productName' -Description 'Clean Windows machine') -notmatch 'Windows' -or
        [string](Get-RequiredJsonProperty -Object $machine -Name 'architecture' -Description 'Clean Windows machine') -notmatch '64' -or
        [string](Get-RequiredJsonProperty -Object $machine -Name 'manufacturer' -Description 'Clean Windows machine') -notmatch '(?i)qemu' -or
        $installAgeHours -lt 0 -or $installAgeHours -gt 24 -or
        @(Get-RequiredJsonProperty -Object $machine -Name 'developerToolsOnPath' -Description 'Clean Windows machine').Count -ne 0 -or
        [int](Get-RequiredJsonProperty -Object $machine -Name 'networkAdaptersUp' -Description 'Clean Windows machine') -ne 0) {
        throw 'Clean Windows host identity, freshness, toolchain, or offline state is not passing.'
    }

    $vmProvenance = Get-RequiredJsonProperty -Object $evidence -Name 'vmProvenance' -Description 'OpenCV clean-machine evidence'
    if ([string](Get-RequiredJsonProperty -Object $vmProvenance -Name 'schema' -Description 'VM provenance') -cne 'graphreader.clean-windows-vm-provenance.v1' -or
        [string](Get-RequiredJsonProperty -Object $vmProvenance -Name 'environmentKind' -Description 'VM provenance') -cne 'fresh-windows-evaluation-vm' -or
        [string](Get-RequiredJsonProperty -Object $vmProvenance -Name 'networkMode' -Description 'VM provenance') -cne 'none') {
        throw 'VM provenance schema or execution boundary is invalid.'
    }
    Assert-JsonBoolean -Object $vmProvenance -Name 'isoSha256Verified' -Expected $true -Description 'VM provenance'
    Assert-JsonBoolean -Object $vmProvenance -Name 'freshInstall' -Expected $true -Description 'VM provenance'
    foreach ($hashField in @('isoSha256', 'officialIsoSha256', 'vmConfigurationSha256', 'qemuInstallerSha256', 'expectedExecutableSha256', 'expectedOpenCvSha256', 'expectedHarnessSha256')) {
        Assert-CanonicalSha256 -Value (Get-RequiredJsonProperty -Object $vmProvenance -Name $hashField -Description 'VM provenance') -Description "VM provenance $hashField"
    }
    if ([string]$vmProvenance.isoSha256 -cne [string]$vmProvenance.officialIsoSha256 -or
        [string]$vmProvenance.expectedCommit -cne $ExpectedCommit -or
        [string]$vmProvenance.expectedVersion -cne $ExpectedVersion -or
        [string]$vmProvenance.expectedExecutableSha256 -cne [string]$payloadExecutableSha256 -or
        [string]$vmProvenance.expectedOpenCvSha256 -cne $ExpectedNativeSha256 -or
        [string]$vmProvenance.expectedHarnessSha256 -cne $ExpectedHarnessSha256 -or
        ([string]$vmProvenance.vmId).ToLowerInvariant() -cne ([string]$machine.machineUuid).ToLowerInvariant() -or
        [string]$vmProvenance.expectedOsBuild -cne [string]$machine.buildNumber -or
        [int]$vmProvenance.expectedOsUbr -ne [int]$machine.updateBuildRevision -or
        [string]::IsNullOrWhiteSpace([string]$vmProvenance.qemuVersion)) {
        throw 'VM provenance does not bind the observed guest, payload, harness, ISO, and runtime.'
    }
}

$releaseAudit = Get-Content -LiteralPath $releaseAuditPath -Raw | ConvertFrom-Json
$components = @($releaseAudit.components | Where-Object {
        [string]$_.id -ceq 'opencvsharp-native'
    })
if ($components.Count -ne 1) {
    throw "Release audit must contain exactly one 'opencvsharp-native' component."
}
$component = $components[0]
$expectedHash = [string]$component.artifactSha256
if ([string]$component.checksumPolicy -cne 'exact-binary' -or
    $expectedHash -notmatch '^[0-9a-fA-F]{64}$') {
    throw "Release OpenCV component must use exact-binary coverage with an artifact SHA-256."
}
$expectedHash = $expectedHash.ToLowerInvariant()

$gates = @($releaseAudit.mandatoryEvidenceGates | Where-Object {
        [string]$_.id -ceq 'opencv-clean-machine-load'
    })
if ($gates.Count -ne 1) {
    throw "Release audit must contain exactly one 'opencv-clean-machine-load' gate."
}
$gate = $gates[0]
if ([string]$gate.status -cne 'pass' -or @($gate.evidence).Count -eq 0) {
    throw "OpenCV clean-machine evidence gate is not directly passing."
}
$gateEvidence = @($gate.evidence)
if ($gateEvidence.Count -ne 1) {
    throw 'OpenCV clean-machine evidence gate must contain exactly one reviewed report.'
}
$cleanMachineHarnessSha256 = (Get-FileHash -LiteralPath $cleanMachineHarnessPath -Algorithm SHA256).Hash.ToLowerInvariant()
$destinationExecutablePath = Join-Path $DestinationRoot 'GraphReader.App.exe'
if (-not (Test-Path -LiteralPath $destinationExecutablePath -PathType Leaf)) {
    throw "Published application executable is missing: $destinationExecutablePath"
}
$destinationExecutableSha256 = (Get-FileHash -LiteralPath $destinationExecutablePath -Algorithm SHA256).Hash.ToLowerInvariant()
foreach ($evidence in @($gate.evidence)) {
    $relativePath = [string]$evidence.path
    $evidenceHash = [string]$evidence.sha256
    if ([IO.Path]::IsPathRooted($relativePath) -or
        $relativePath -match '(^|[\\/])\.\.([\\/]|$)' -or
        $evidenceHash -notmatch '^[0-9a-fA-F]{64}$') {
        throw "OpenCV clean-machine evidence uses an unsafe path or invalid checksum."
    }
    $evidencePath = [IO.Path]::GetFullPath((Join-Path $RepositoryRoot $relativePath))
    if (-not $evidencePath.StartsWith($repositoryPrefix, [StringComparison]::OrdinalIgnoreCase) -or
        -not (Test-Path -LiteralPath $evidencePath -PathType Leaf)) {
        throw "OpenCV clean-machine evidence is missing or outside the repository: $relativePath"
    }
    $actualEvidenceHash = (Get-FileHash -LiteralPath $evidencePath -Algorithm SHA256).Hash.ToLowerInvariant()
    if (-not [string]::Equals($actualEvidenceHash, $evidenceHash, [StringComparison]::OrdinalIgnoreCase)) {
        throw "OpenCV clean-machine evidence checksum differs: $relativePath"
    }
    Assert-CleanMachineEvidence `
        -Path $evidencePath `
        -ExpectedNativeSha256 $expectedHash `
        -ExpectedHarnessSha256 $cleanMachineHarnessSha256 `
        -ExpectedExecutableSha256 $destinationExecutableSha256
}

& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $installerPath `
    -EvidenceRoot $EvidenceRoot `
    -DestinationRoot $DestinationRoot `
    -RepositoryRoot $RepositoryRoot
if ($LASTEXITCODE -ne 0) {
    throw "Reviewed OpenCV runtime installation failed with exit code $LASTEXITCODE."
}

$metadataPath = Join-Path $DestinationRoot 'reviewed-opencv-runtime.json'
$metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
if ([string]$metadata.binarySha256 -cne $expectedHash -or
    -not [bool]$metadata.provenanceValidated -or
    [string]$metadata.noticeReviewStatus -cne 'complete' -or
    [bool]$metadata.cleanMachineEvidence -or
    [bool]$metadata.releaseApproved) {
    throw "Reviewed OpenCV runtime does not match the exact release-audit boundary."
}

$metadata.cleanMachineEvidence = $true
$metadata.releaseApproved = $true
[IO.File]::WriteAllText(
    $metadataPath,
    (($metadata | ConvertTo-Json -Depth 10) + [Environment]::NewLine),
    [Text.UTF8Encoding]::new($false))

Write-Host "Release-approved OpenCV runtime installed: $($metadata.binarySha256)"
Write-Output ([pscustomobject]@{
    DestinationPath = Join-Path $DestinationRoot 'OpenCvSharpExtern.dll'
    MetadataPath = $metadataPath
    BinarySha256 = [string]$metadata.binarySha256
    CleanMachineEvidence = $true
    ReleaseApproved = $true
})
