# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Sungwoo Kang

is_debug = false
is_component_build = false
target_os = "win"
target_cpu = "x64"
symbol_level = 0
pdf_is_standalone = true
pdf_is_complete_lib = false
pdf_enable_v8 = false
pdf_enable_xfa = false
pdf_use_skia = false
pdf_enable_fontations = false
pdf_use_partition_alloc = false
icu_use_data_file = false
treat_warnings_as_errors = true
